name: Deploy k0s Cluster on Hetzner

on:
  workflow_dispatch:
    inputs:
      hetzner_token:
        description: 'Hetzner API Token'
        required: true
      ssh_key:
        description: 'SSH Key Name in Hetzner Cloud'
        required: true
        default: 'tadas@DESKTOP-638FCAG'
      server_type_controller:
        description: 'Server type for controller node'
        required: true
        default: 'cax11'
      server_type_worker:
        description: 'Server type for worker nodes'
        required: true
        default: 'cax11'
      location:
        description: 'Hetzner location'
        required: true
        default: 'nbg1'
      k0s_version:
        description: 'k0s version'
        required: true
        default: 'v1.28.4+k0s.0'

env:
  HCLOUD_TOKEN: ${{ github.event.inputs.hetzner_token }}
  TF_VAR_hcloud_token: ${{ github.event.inputs.hetzner_token }}
  TF_VAR_ssh_key: ${{ github.event.inputs.ssh_key }}
  TF_VAR_server_type_controller: ${{ github.event.inputs.server_type_controller }}
  TF_VAR_server_type_worker: ${{ github.event.inputs.server_type_worker }}
  TF_VAR_location: ${{ github.event.inputs.location }}
  TF_VAR_k0s_version: ${{ github.event.inputs.k0s_version }}
  TF_VAR_ssh_private_key_path: "~/.ssh/id_rsa"

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Install Hetzner CLI
        run: |
          wget -O /tmp/hcloud_linux.tar.gz https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz
          tar -xzf /tmp/hcloud_linux.tar.gz -C /tmp
          sudo mv /tmp/hcloud /usr/local/bin/
          hcloud version

      - name: Install k0sctl
        run: |
          # Download the specific k0sctl binary for Linux
          wget -O k0sctl https://github.com/k0sproject/k0sctl/releases/download/v0.22.0/k0sctl-linux-amd64
          chmod +x k0sctl
          sudo mv k0sctl /usr/local/bin/
          k0sctl version

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Create Terraform Plan
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan

      - name: Wait for servers to be ready
        run: sleep 60  # Increased wait time to ensure servers are fully ready

      - name: Generate k0sctl.yaml configuration
        run: |
          CONTROLLER_IPS=$(terraform output -json controller_ips | jq -r '.[]')
          WORKER_IPS=$(terraform output -json worker_ips | jq -r '.[]')
          CONTROLLER_PRIVATE_IPS=$(terraform output -json controller_private_ips | jq -r '.[]')
          WORKER_PRIVATE_IPS=$(terraform output -json worker_private_ips | jq -r '.[]')
          LOADBALANCER_IP=$(terraform output -raw loadbalancer_ip)
          
          cat > k0sctl.yaml << EOF
          apiVersion: k0sctl.k0sproject.io/v1beta1
          kind: Cluster
          metadata:
            name: k0s-cluster
          spec:
            hosts:
          EOF

          i=0
          for ext_ip in $CONTROLLER_IPS; do
            priv_ip=$(echo $CONTROLLER_PRIVATE_IPS | jq -r ".[$i]")
            cat >> k0sctl.yaml << EOF
              - ssh:
                  address: $ext_ip
                  user: root
                  port: 22
                  keyPath: ~/.ssh/id_rsa
                role: controller+worker
                privateAddress: $priv_ip
                installFlags:
                  - --kubelet-extra-args=--cloud-provider=external
            EOF
            i=$((i+1))
          done

          i=0
          for ext_ip in $WORKER_IPS; do
            priv_ip=$(echo $WORKER_PRIVATE_IPS | jq -r ".[$i]")
            cat >> k0sctl.yaml << EOF
              - ssh:
                  address: $ext_ip
                  user: root
                  port: 22
                  keyPath: ~/.ssh/id_rsa
                role: worker
                privateAddress: $priv_ip
                installFlags:
                  - --kubelet-extra-args=--cloud-provider=external
          EOF
            i=$((i+1))
          done

          cat >> k0sctl.yaml << EOF
            k0s:
              version: ${{ github.event.inputs.k0s_version }}
              config:
                apiVersion: k0s.k0sproject.io/v1beta1
                kind: Cluster
                metadata:
                  name: hetzner-k0s
                spec:
                  api:
                    externalAddress: $LOADBALANCER_IP
                    sans:
                      - $LOADBALANCER_IP
          EOF

          for ext_ip in $CONTROLLER_IPS; do
            echo "                      - $ext_ip" >> k0sctl.yaml
          done

          cat >> k0sctl.yaml << EOF
                    k0sApiPort: 9443
                    port: 6443
                  installConfig:
                    users:
                      etcdUser: etcd
                      kineUser: kube-apiserver
                      konnectivityUser: konnectivity-server
                      kubeAPIserverUser: kube-apiserver
                      kubeSchedulerUser: kube-scheduler
                  konnectivity:
                    adminPort: 8133
                    agentPort: 8132
                  network:
                    kubeProxy:
                      disabled: false
                      mode: iptables
                    kuberouter:
                      autoMTU: true
                      mtu: 0
                      peerRouterASNs: ""
                      peerRouterIPs: ""
                    podCIDR: 10.244.0.0/16
                    provider: kuberouter
                    serviceCIDR: 10.96.0.0/12
                  storage:
                    type: etcd
                  telemetry:
                    enabled: true
          EOF


      - name: Deploy k0s cluster
        run: k0sctl apply --config k0sctl.yaml --debug

      - name: Get kubeconfig
        run: |
          k0sctl kubeconfig --config k0sctl.yaml > kubeconfig

      - name: Test cluster connection
        run: |
          export KUBECONFIG=./kubeconfig
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods --all-namespaces

      - name: Save kubeconfig as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubeconfig
          path: kubeconfig

      - name: Save Terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: |
            terraform.tfstate
            terraform.tfstate.backup

      - name: Create cluster info file
        run: |
          CONTROLLER_IP=$(terraform output -raw controller_ip)
          WORKER_IPS=$(terraform output -json worker_ips)
          NETWORK_ID=$(terraform output -raw network_id)
          
          cat > cluster-info.txt << EOF
          Controller Node: ${CONTROLLER_IP}
          Worker Nodes: ${WORKER_IPS}
          Hetzner Network ID: ${NETWORK_ID}
          K0s Version: ${{ github.event.inputs.k0s_version }}
          Deployment Time: $(date)
          EOF
          
      - name: Save cluster info
        uses: actions/upload-artifact@v4
        with:
          name: cluster-info
          path: cluster-info.txt